### ISSUE TITLE
用这个插件重启Mucisbee就会报错

### ISSUE THREAD

**Issue by Hinonefor** [cqjjjzr/MusicBee-DesktopLyrics#12]
# 下面是日志：

`MusicBee v3.4.8033.18564D  (Win10.0), 7 6月 2022 10:26:

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   在 System.Windows.Forms.Application.ExitInternal()
   在 System.Windows.Forms.Application.Exit(CancelEventArgs e)
   在 #=zZayNzbiQusTiMxpjyrnkLZz66MZF.#=zAEUqCQY=.#=zwNal2xPhZlbo(Boolean #=zLgoRd$umPwQy)
   在 #=zZayNzbiQusTiMxpjyrnkLZz66MZF.#=z5nQ7oDRHwxuM.#=z$UMzyBPSEM3cDKyCRA==(Object #=z09rm0$E=, FormClosedEventArgs #=z5EKpxKY=)
   在 System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   在 System.Windows.Forms.Form.WmClose(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 #=z6OpcwAtd4LyLqAQX94gnWtM=.WndProc(Message& #=zvynw6wQ=)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by cqjjjzr** [comment]
有没有其它插件？重启MB之前桌面歌词处于哪个状态？似乎这和多线程有关？

另外这个问题能稳定复现吗（每次重启都发生？）

**Comment by Hinonefor** [comment]
> 有没有其它插件？重启MB之前桌面歌词处于哪个状态？似乎这和多线程有关？
> 
> 另外这个问题能稳定复现吗（每次重启都发生？）

有其他插件的，除了自带的就是封面查找和网易云歌词查找。歌词是正常的。可以复现的，要截图吗？

**Comment by cqjjjzr** [comment]
感觉定位到了一个可疑的点，但我这边没法复现，要不我等会改了发你试试？

**Comment by cqjjjzr** [comment]
试试这个
[mb_DesktopLyrics.zip](https://github.com/cqjjjzr/MusicBee-DesktopLyrics/files/8853731/mb_DesktopLyrics.zip)
：

**Comment by Hinonefor** [comment]
> 试试这个 [mb_DesktopLyrics.zip](https://github.com/cqjjjzr/MusicBee-DesktopLyrics/files/8853731/mb_DesktopLyrics.zip) ：

现在可以了，重启不再报错了
