### ISSUE TITLE
关于双行歌词显示

### ISSUE THREAD

**Issue by wulingyijiu** [cqjjjzr/MusicBee-DesktopLyrics#14]
![image](https://user-images.githubusercontent.com/46135524/183280818-98e99415-db5f-4de5-b107-b3b26d4fd3b4.png)
如图，怎么做才可以减少歌词间距，这样的话将会完美“嵌入”任务栏
另外双行模式在只有一行信息时（如无歌词 只显示歌名）会默认显示在上行，调整到中间显示会更美观一些

**Comment by cqjjjzr** [comment]
这个看上去是个DPI相关的问题啊……您用的哪个插件版本来着

**Comment by wulingyijiu** [comment]
插件版本是1.6.1 也就是四天前更新的那个
屏幕是16：10 dpi是系统推荐的200%

**Comment by cqjjjzr** [comment]
那应该是DPI问题没修好了……我晚些时候看下

@LasmGratel 您有何看法 我感觉是缩放不为100%时，[这里渲染第一行](https://github.com/cqjjjzr/MusicBee-DesktopLyrics/blob/8cd6d710898fee125acb3308c9400d80c73926cb/LyricsRenderer.cs#L56)的时候出来的bitmap大小有错误

**Comment by LasmGratel** [comment]
我觉得是间距也一块 DPI aware 了

**Comment by LasmGratel** [comment]
可以尝试将这一行
https://github.com/cqjjjzr/MusicBee-DesktopLyrics/blob/8cd6d710898fee125acb3308c9400d80c73926cb/LyricsRenderer.cs#L56
的 0.8f 修改成 0.6f，也可以提供一个选项来修改行间距

**Comment by cqjjjzr** [comment]
这里嗯编码总是不对的，感觉这个 `line1Bitmap` 的高度就是没算对的

**Comment by cqjjjzr** [comment]
See https://github.com/cqjjjzr/MusicBee-DesktopLyrics/releases/tag/v1.7.0

**Comment by wulingyijiu** [comment]
![image](https://user-images.githubusercontent.com/46135524/183321390-36c9e9ca-07f0-4fe7-9f20-03666364fed5.png)
好，非常感谢
