### ISSUE TITLE
Only show song title

### ISSUE THREAD

**Issue by vathanac** [cqjjjzr/MusicBee-DesktopLyrics#15]
![image](https://user-images.githubusercontent.com/87689818/214278109-fdc81335-0f6e-4bd5-b48f-02ea4eedeb11.png)

**Comment by vathanac** [comment]
https://github.com/cqjjjzr/MusicBee-NeteaseLyricshttps://github.com/cqjjjzr/MusicBee-NeteaseLyrics

Working rn after install this plugin but is there any better lyric provider alternative?

**Comment by cqjjjzr** [comment]
There should be plenty. Try to look up in the MusicBee's addon gallery.
