### ISSUE TITLE
能否增加一个双行歌词的选项

### ISSUE THREAD

**Issue by cjchnws3** [cqjjjzr/MusicBee-DesktopLyrics#16]
大佬，下次更新时，能增加一个类似于网易音乐那种，双行歌词显示的选项吗？因为有时歌词上下句可能时间没那么准确，会错位零点几秒。如果在显示当前行歌词的同时，同时显示下一行作为缓冲，观感上可能会更好一些。感谢大佬！
![截图](https://user-images.githubusercontent.com/94509244/222028216-bb94b0cd-d887-432e-8644-f3c5be4efceb.png)

**Comment by cqjjjzr** [comment]
单语言的歌词可能可以做下 双语的因为本来就要占两行，不是特别好做（因为现在代码写得比较死（

**Comment by cjchnws3** [comment]
嗯嗯，双语的网易云也是占两行，不好改的。不过单语言的，大佬可以试试看('ヮ')

**Comment by cqjjjzr** [comment]
Closed as completed and due to inactivity,

**Comment by cjchnws3** [comment]
我去！刚看到消息。厉害了大佬，很完美，感谢感谢！o(^▽^)o
