### ISSUE TITLE
Wrong interpretation of characters "[]" and "/"

### ISSUE THREAD

**Issue by seaspeak** [cqjjjzr/MusicBee-DesktopLyrics#2]
Everything after "["  is discarded.
"/" in lyrics, is viewed as an newline character, which is not necessary.

[SONY's implementation](http://docs.esupport.sony.com/portable/NWZE353_E354_E355_guide/eng/contents/03/05/11/11.html#l3_notes)

**Comment by cqjjjzr** [comment]
the "/" is designed to be viewed as a newline character in order to cooperate with the "Netease Lyrics" plugin developed by me, which use "/" to separate the lyrics and translation.

**Comment by seaspeak** [comment]
I see. 
But "/" is ubiquitous. It may be less common in music lyrics, but lrc could also be used for literature or for  any other learning purpose. That is why I think correctly interpretation of "/" and "[" is also important.
[supporting lengthy music, longer than 60 minutes, is also good]

**Comment by cqjjjzr** [comment]
Maybe I will add a option to decide if "/" should be considered as separators in the coming version.

**Comment by cqjjjzr** [comment]
closed by #8. Will be available in version 1.3.
