### ISSUE TITLE
Hotkey for togging desktop lyrics on/off does not work.

### ISSUE THREAD

**Issue by soarpasser** [cqjjjzr/MusicBee-DesktopLyrics#22]
Since there is no option in the player or plugin to quickly toggle the lyrics on/off, I've manually assigned a hotkey to the view>Desktop Lyrics option.
![image](https://github.com/user-attachments/assets/2a75d74a-eff5-4301-ac03-b27cf850a976)
![image](https://github.com/user-attachments/assets/41fa0ed8-4d36-4b40-a6e4-de2a54da791f)
However this simply doesn't work as pressing the assigned hotkey doesn't do anything. The user has to go into the menu manually to toggle the lyrics on/off.

This should be very easy to reproduce and hopefully fix.

**Comment by cqjjjzr** [comment]
fixed in 1.8.2.

https://github.com/cqjjjzr/MusicBee-DesktopLyrics/releases/tag/v1.8.2
