### ISSUE TITLE
能够增加歌词左/右对齐的选项

### ISSUE THREAD

**Issue by beingwish** [cqjjjzr/MusicBee-DesktopLyrics#23]
目前只能放在屏幕中间，放在左右两边歌词句子一长就会超出屏幕范围，能否增加左/右对齐的选项，方便放在两侧

**Comment by cqjjjzr** [comment]
Completed in https://github.com/cqjjjzr/MusicBee-DesktopLyrics/releases/tag/v1.9.0 .
