### ISSUE TITLE
Desktop lyric font size too small

### ISSUE THREAD

**Issue by garylavayou** [cqjjjzr/MusicBee-DesktopLyrics#4]
I use a 4K screen, the font size is set as "初号"， the display words are still very small.

Maybe the scaling factor should be considered.

**Comment by cqjjjzr** [comment]
Can enabling DPI awareness fix that?

**Comment by garylavayou** [comment]
> Can enabling DPI awareness fix that?

I have installed the Store version, the DPI related setting is not available for the application.

**Comment by LasmGratel** [comment]
https://github.com/LasmGratel/MusicBee-DesktopLyrics/releases/tag/v1.3.0

**Comment by cqjjjzr** [comment]
Closed by #9. will be included in ver 1.3.
