### ISSUE TITLE
大佬，有可能暂时隐藏桌面歌词吗？

### ISSUE THREAD

**Issue by Rereyuop** [cqjjjzr/MusicBee-DesktopLyrics#5]
不播歌的时候隐藏也好啊。不知道蜜蜂支不支持。
我注意到字体的阴影是往左上飘的，能不能也自定义一下，像隔壁Karaoke那样，不过它的模糊渲染太差劲了..

**Comment by cqjjjzr** [comment]
点 视图-Desktop Lyrics 就隐藏啊，近期会发的新版会加上不放歌的时候隐藏

**Comment by cqjjjzr** [comment]
fixed in v1.5.0
