### ISSUE TITLE
Desktop Lyrics Bugged (Please Help Me)

### ISSUE THREAD

**Issue by Klubuntu** [cqjjjzr/MusicBee-DesktopLyrics#7]
#Desktop Lyrics Bugged (Please Help Me)

MusicBee v3.3.7491.38139D  (Win10.0), 12 lis 2020 13:59:

System.NullReferenceException: Object reference not set to an instance of an object.
   w MusicBeePlugin.LyricsRenderer.RenderLyrics(String lyric, Font font)
   w MusicBeePlugin.FrmLyrics.DrawLyrics1Line(String lyrics)
   w MusicBeePlugin.FrmLyrics.Redraw()
   w MusicBeePlugin.FrmLyrics.UpdateLyrics(String line1, String line2)
   w MusicBeePlugin.Plugin.<UpdateLyrics>b__207_0(String line1, String line2)
CODE
<a href="https://imgur.com/a/7Erm8i4"/>

**Comment by cqjjjzr** [comment]
Try to delete `desktopLyrics.json` in `C:\Users\(your username)\AppData\Roaming\MusicBee`

**Comment by Klubuntu** [comment]
### @cqjjjzr
I'll try to use this method :blush:  today

**Comment by Klubuntu** [comment]
****

**Comment by cqjjjzr** [comment]
Closed due to inactivity.
